apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Hontokun-frontend
  namespace: argocd

spec:
  destination:
    namespace: hontokun
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: hontokun-backend
      repoURL: https://kouxi08.github.io/Hontokun-frontend/
      targetRevision: v1.0.0
  project: default
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
