apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hontokun-frontend
  namespace: argocd

spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/hontokun
    repoURL: https://github.com/kouxi08/Hontokun-frontend.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
