apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd

spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  sources:
      repoURL: https://github.com/kouxi08/k8s-manifesto.git
      path: longhorn
      targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

