apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog
spec:
  template:
    spec:
      containers:
        - image: kouxi00/astro-blog
          ports:
            - containerPort: 4321
