prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.local.kouxi.jp
    ingressClassName: nginx

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.local.kouxi.jp
    ingressClassName: nginx