grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.local.kouxi.jp
    ingressClassName: nginx

alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.local.kouxi.jp
    ingressClassName: nginx

prometheus:
 config:
  global:
    resolve_timeout: 5m
  inhibit_rules:
    - source_matchers:
        - 'severity = critical'
      target_matchers:
        - 'severity =~ warning|info'
      equal:
        - 'namespace'
        - 'alertname'
    - source_matchers:
        - 'severity = warning'
      target_matchers:
        - 'severity = info'
      equal:
        - 'namespace'
        - 'alertname'
    - source_matchers:
        - 'alertname = InfoInhibitor'
      target_matchers:
        - 'severity = info'
      equal:
        - 'namespace'
  route:
    group_by: [ 'alertname', 'job' ]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: discord
  receivers:
    - name: discord
      discord_configs:
        - apiURL:
            name: alertmanager-secret
            key: webhook-url
    - name: 'null'
  templates:
    - '/etc/alertmanager/config/*.tmpl'
  ingress:
    enabled: true
    hosts:
      - prometheus.local.kouxi.jp
    ingressClassName: nginx
