bases:
  - environments.yaml

repositories:
  - name: zabbix-community
    url: https://zabbix-community.github.io/helm-zabbix

releases:
  - name: zabbix
    namespace: zabbix
    chart: zabbix-community/zabbix
    version: 7.1.0