bases:
  - environments.yaml

repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-chart

releases:
  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/kube-prometheus-stack
    version: 68.2.1
    values:
      - ./env/values.yaml