apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-application
  namespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  source:
    repoURL: https://github.com/kouxi08/k8s-manifesto.git
    path: metrics-server
    targetRevision: main
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
