apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-application
  namespace: argocd

spec:
  destination:
    namespace: blog
    server: 'https://kubernetes.default.svc'
  source:
    path: blog
    repoURL: https://github.com/kouxi08/k8s-manifesto.git
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
