apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-blog
  template:
    metadata:
      labels:
        app: astro-blog
    spec:
      containers:
      - name: astro-blog
        image: kouxi00/astro-blog
        env:
        - name: MICROCMS_SERVICE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: service-domain
        - name: MICROCMS_API_KEY
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: api_key
        - name: ENDPOINT
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: endpoint
        - name: USE_SSL
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: use_ssl
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: access_key
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: secret_access_key
        ports:
        - containerPort: 4321

---
apiVersion: v1
kind: Service
metadata:
  name: astro-blog-svc
spec:
  selector:
    app: astro-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4321

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-blog-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: blog.kouxi.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: astro-blog-svc
            port:
              number: 80
