apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astro-blog
  template:
    metadata:
      labels:
        app: astro-blog
    spec:
      containers:
      - name: astro-blog
        image: kouxi08/astro-blog
        ports:
        - containerPort: 4321

---

apiVersion: v1
kind: Service
metadata:
  name: astro-blog
spec:
  selector:
    app: astro-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4321
  type: LoadBalancer  # サービスの公開にはLoadBalancerを使用する例
