bases:
  - environments.yaml

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.25.2
  - name: istio-istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.25.2
  - name: istio-gateway
    namespace: istio-system
    chart: istio/gateway
    version: 1.25.2