bases:
  - environments.yaml

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio
    namespace: istio-system
    chart: istio/gateway
    version: 1.24.3