apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hontokun
  namespace: argocd

spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: hontokun/apps
    repoURL: https://github.com/kouxi08/k8s-manifesto.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
