apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hontokun-frontend
  namespace: argocd

spec:
  destination:
    namespace: hontokun
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/kouxi08/k8s-manifesto.git
    path: hontokun/frontend
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
